name: "suite-ai"

services:
  open-chainprompt-ai-collaudo:
    image: open-chainprompt-ai-collaudo:${IMG_VERSION:-latest}
    container_name: open-chainprompt-ai-collaudo
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5500:5000"
      - "6000:6000"      
    env_file:
      - ./.env.collaudo
    networks:
      - network-open-chainprompt-docker
    volumes:
      - ./src/datasets/fileset/conversations:/app/datasets/fileset/conversations
      - ./:/usr/app
      - /usr/app/node_modules      
    entrypoint: ./entry-point.sh 


networks:
  network-open-chainprompt-docker:
    driver: bridge